server:
  port: 8082

spring:
  application:
    name: swinnus.mqttsub
  
  # Database Configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/mqtt
    username: root
    password: rokaf308!@#
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        cache:
          use_second_level_cache: false

# MQTT Configuration
mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: demo3Client
  topic: test/topic

# Logging Configuration
logging:
  level:
    org:
      springframework:
        integration:
          mqtt: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      swinnus:
        mqttsub: DEBUG 